parameters:
  rss.url_collection: ['https://g1.globo.com/rss/g1/ciencia-e-saude/',
                       'https://g1.globo.com/rss/g1/mundo/',
                       'https://g1.globo.com/rss/g1/planeta-bizarro/',
                       'https://g1.globo.com/rss/g1/tecnologia/',
                       'https://g1.globo.com/rss/g1/turismo-e-viagem/',
                       'https://g1.globo.com/rss/g1/distrito-federal/',
                       'https://gizmodo.uol.com.br/feed/',]

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
